### ISSUE TITLE
小白部署完了 请问默认上传到那里 还有能不能上传到群

### ISSUE THREAD

**Issue by hibiki222** [SkyDependence/tgDrive#33]

**Comment by StanleyLegEnd1024** [comment]
是上传到chat_id对应的用户的，你可以填写自己的chat_id，这样文件全部分片传入你与机器人的私聊

**Comment by SkyDependence** [comment]
> 2025-08-30 12:23:24 Caused by: java.lang.NullPointerException: Cannot invoke "com.pengrad.telegrambot.TelegramBot.execute(com.pengrad.telegrambot.request.BaseRequest)" because "bot" is null

这看起来像是bot token没设置，你的配置文件正确填写了吗？在网盘管理的“机器人保活”里，点击发送保活消息，看看你的telegram是否接收到了消息

**Comment by SkyDependence** [comment]
> services must be a mapping

这个错误是因为yml的缩进不对，要照着readme里写的缩进

```yml
services:
  tgdrive:
    image: nanyangzesi/tgdrive:latest
    container_name: tgdrive
    ports:
      - "8085:8085"
    volumes:
      - ./db:/app/db
    restart: always
```
